var app=angular.module('fundooApp',['ui.router','ngMaterial']);
app.config(function($stateProvider,$urlRouterProvider)
{
  $stateProvider
  .state('Register',
  {
    url:'/Register',
    templateUrl:'templates/register.html',
    controller:'userCtrl'
  })
  .state('Login',
{
  url:'/login',
  templateUrl:'templates/login.html',
  controller:'userCtrl'
})
.state('forgotPassword',
{
  url:'/forgotPassword',
  templateUrl:'templates/forgotPassword.html',
  controller:'userCtrl'
})
.state('resetPassword',
{
url:'/resetPassword/:token',
templateUrl: 'templates/resetPassword.html',
controller:'userCtrl',
params: {
        token: null,
}
})
.state('home',
 {
   url:'/home',
   templateUrl:'templates/home.html',
   controller:'homeCtrl'
})
.state('home.dashboard',
 {
   url:'/dashboard',
   templateUrl:'templates/dashboard.html',
   controller:'noteCtrl'
})
.state('home.dashboard.logout',
{
  url:'/Logout',
  templateUrl:'templates/logout.html',
  controller:'homeCtrl'
})
.state('Trash',
{
  url:'/trashnote',
  templateUrl:'templates/trashnote.html',
  controller:'homeCtrl'
})
.state('Note',
{
  url:'/note',
  templateUrl:'templates/note.html',
  controller:'homeCtrl'
})
.state('Reminder',
{
  url:'/reminder',
  templateUrl:'templates/reminder.html',
  controller:'homeCtrl'
})

  $urlRouterProvider.otherwise("/Register")
});
